using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using EnvDTE;
using Microsoft.VisualStudio;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;

namespace Reflgen.VisualStudio
{
    // 생성을 돌릴 프로젝트 하나 — 활성 구성 기준.
    internal sealed record ProjectTarget(string ProjectFile, string DisplayName, string Configuration, string Platform,
                                         IVsHierarchy Hierarchy);

    // VS 프로젝트 시스템과의 경계. 모두 UI 스레드에서 부른다. reflgen.targets 가 정한 속성을
    // IVsBuildPropertyStorage 로 읽는다(.vcxproj 가 MSBuild 로 평가한 값이다). 프로젝트 파일에는 쓰지 않는다.
    internal sealed class ProjectBridge
    {
        private const string ImportedProperty = "ReflgenTargetsImported";
        private const string CatalogProperty = "ReflgenCatalogFile";
        private const string OutputDirectoryProperty = "ReflgenOutputDirectory";
        private const string ModuleProperty = "ReflgenModule";
        private const string RescanSolutionCommand = "Project.RescanSolution";
        // 생성기가 쓴 파일의 머리말 — design-time build 가 먼저 두는 빈 주입 header 에는 없다.
        private const string GeneratedBanner = "<auto-generated/> Generated by reflgen";

        private readonly IServiceProvider _services;

        public ProjectBridge(IServiceProvider services)
        {
            _services = services;
        }

        public bool UsesReflgen(IVsHierarchy hierarchy)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            return string.Equals(GetProperty(hierarchy, ImportedProperty), "true", StringComparison.OrdinalIgnoreCase);
        }

        // 생성물이 놓이는 빌드 중간 산출물 디렉터리(활성 구성).
        public string? OutputDirectory(IVsHierarchy hierarchy)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            string? directory = GetProperty(hierarchy, OutputDirectoryProperty);
            return string.IsNullOrEmpty(directory) ? null : directory;
        }

        // 아직 한 번도 생성하지 않았는가 — 주입 header 가 없거나 design-time build 가 둔 빈 자리표시자다. 이대로면
        // IntelliSense 가 reflection 을 보지 못하므로 프로젝트를 열 때 한 번 생성한다.
        public bool NeedsFirstGeneration(IVsHierarchy hierarchy)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            string? directory = OutputDirectory(hierarchy);
            string? module = GetProperty(hierarchy, ModuleProperty);
            if (directory == null || string.IsNullOrEmpty(module))
            {
                return false;
            }
            string injection = Path.Combine(directory, "reflgen_" + module + ".h");
            return !File.Exists(injection) || !File.ReadAllText(injection).Contains(GeneratedBanner);
        }

        // 불러온 프로젝트 가운데 reflgen.targets 를 가져온 것.
        public IReadOnlyList<IVsHierarchy> ReflgenProjects()
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            var projects = new List<IVsHierarchy>();
            foreach (IVsHierarchy project in LoadedProjects())
            {
                if (UsesReflgen(project))
                {
                    projects.Add(project);
                }
            }
            return projects;
        }

        // 이 header 의 생성 파일이 있는가 — 반영을 지운 header 를 저장했을 때도 다시 생성해 옛 서술을 걷어 내려고 본다.
        public bool WasGenerated(IVsHierarchy hierarchy, string headerPath)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            string? directory = OutputDirectory(hierarchy);
            return directory != null && File.Exists(Path.Combine(directory, ReflectedHeader.GeneratedHeaderName(headerPath)));
        }

        // IntelliSense 는 프로젝트 밖에 있는 강제 include 파일이 바뀐 것을 스스로 알아채지 못한다 — C++ 의 "검색
        // 데이터베이스 새로 고침"(Project.RescanSolution)으로 다시 읽힌다. 명령은 이름으로 부른다.
        public bool RefreshIntelliSense(out string problem)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            if (_services.GetService(typeof(SDTE)) is not DTE automation)
            {
                problem = "the automation model (DTE) is not available";
                return false;
            }
            try
            {
                automation.ExecuteCommand(RescanSolutionCommand);
                problem = string.Empty;
                return true;
            }
            catch (Exception exception) when (exception is COMException || exception is ArgumentException)
            {
                // 명령이 없거나(C++ 워크로드 없음) 지금은 쓸 수 없다.
                problem = $"{RescanSolutionCommand} could not run ({exception.Message.Trim()})";
                return false;
            }
        }

        // 못 찾으면 null 과 함께 이유를 돌려준다 — 호출자가 Output 창에 남긴다.
        public ProjectTarget? TargetOf(IVsHierarchy hierarchy, out string problem)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            string? projectFile = ProjectFileOf(hierarchy);
            if (projectFile == null)
            {
                problem = "could not find the project file";
                return null;
            }
            string configuration = ActiveConfigurationName(hierarchy) ?? string.Empty;
            string[] parts = configuration.Split('|');
            if (parts.Length != 2)
            {
                problem = $"could not read the active configuration of {Path.GetFileName(projectFile)} ('{configuration}')";
                return null;
            }
            problem = string.Empty;
            hierarchy.GetProperty(VSConstants.VSITEMID_ROOT, (int)__VSHPROPID.VSHPROPID_Name, out object name);
            return new ProjectTarget(projectFile, name as string ?? Path.GetFileNameWithoutExtension(projectFile),
                                     parts[0], parts[1], hierarchy);
        }

        // 프로젝트 파일 경로. IVsHierarchy.GetCanonicalName 은 프로젝트 시스템마다 뜻이 달라(.vcxproj 경로가
        // 아닐 수 있다) 문서 경로를 주는 IVsProject.GetMkDocument 를 먼저 쓴다.
        private static string? ProjectFileOf(IVsHierarchy hierarchy)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            if (hierarchy is IVsProject project &&
                project.GetMkDocument(VSConstants.VSITEMID_ROOT, out string document) == VSConstants.S_OK &&
                File.Exists(document))
            {
                return document;
            }
            if (hierarchy.GetCanonicalName(VSConstants.VSITEMID_ROOT, out string canonical) == VSConstants.S_OK &&
                File.Exists(canonical))
            {
                return canonical;
            }
            return null;
        }

        public IEnumerable<string> CatalogFiles()
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            var files = new List<string>();
            foreach (IVsHierarchy project in LoadedProjects())
            {
                string? file = UsesReflgen(project) ? GetProperty(project, CatalogProperty) : null;
                if (!string.IsNullOrEmpty(file))
                {
                    files.Add(file!);
                }
            }
            return files;
        }

        public string? SolutionFile()
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            var solution = (IVsSolution)_services.GetService(typeof(SVsSolution));
            if (solution == null || solution.GetSolutionInfo(out _, out string file, out _) != VSConstants.S_OK)
            {
                return null;
            }
            return string.IsNullOrEmpty(file) ? null : file;
        }

        // VS 빌드가 도는 중이면 생성은 그 빌드가 한다.
        public bool IsBuildRunning()
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            var builds = (IVsSolutionBuildManager2)_services.GetService(typeof(SVsSolutionBuildManager));
            if (builds == null || builds.QueryBuildManagerBusy(out int busy) != VSConstants.S_OK)
            {
                return false;
            }
            return busy != 0;
        }

        // 이 VS 에 딸린 MSBuild. 64비트판을 먼저 쓴다.
        public string? BundledMSBuild()
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            var shell = (IVsShell)_services.GetService(typeof(SVsShell));
            if (shell == null ||
                shell.GetProperty((int)__VSSPROPID.VSSPROPID_InstallDirectory, out object directory) != VSConstants.S_OK)
            {
                return null;
            }
            // InstallDirectory 는 <VS>\Common7\IDE\ 다.
            string root = Path.GetFullPath(Path.Combine((string)directory, "..", ".."));
            foreach (string candidate in new[] { @"MSBuild\Current\Bin\amd64\MSBuild.exe", @"MSBuild\Current\Bin\MSBuild.exe" })
            {
                string path = Path.Combine(root, candidate);
                if (File.Exists(path))
                {
                    return path;
                }
            }
            return null;
        }

        private string? GetProperty(IVsHierarchy hierarchy, string name)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            if (hierarchy is not IVsBuildPropertyStorage storage)
            {
                return null;
            }
            // 출력 경로 같은 값은 구성마다 다르다 — 활성 구성으로 평가한다.
            return storage.GetPropertyValue(name, ActiveConfigurationName(hierarchy),
                                            (uint)_PersistStorageType.PST_PROJECT_FILE, out string value) == VSConstants.S_OK
                       ? value
                       : null;
        }

        // "Debug|x64"
        private string? ActiveConfigurationName(IVsHierarchy hierarchy)
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            var builds = (IVsSolutionBuildManager2)_services.GetService(typeof(SVsSolutionBuildManager));
            var configurations = new IVsProjectCfg[1];
            if (builds == null ||
                builds.FindActiveProjectCfg(IntPtr.Zero, IntPtr.Zero, hierarchy, configurations) != VSConstants.S_OK ||
                configurations[0] == null)
            {
                return null;
            }
            return configurations[0].get_CanonicalName(out string name) == VSConstants.S_OK ? name : null;
        }

        private IEnumerable<IVsHierarchy> LoadedProjects()
        {
            ThreadHelper.ThrowIfNotOnUIThread();
            var solution = (IVsSolution)_services.GetService(typeof(SVsSolution));
            var projects = new List<IVsHierarchy>();
            Guid any = Guid.Empty;
            if (solution == null ||
                solution.GetProjectEnum((uint)__VSENUMPROJFLAGS.EPF_LOADEDINSOLUTION, ref any, out IEnumHierarchies items) !=
                    VSConstants.S_OK)
            {
                return projects;
            }
            var batch = new IVsHierarchy[1];
            while (items.Next(1, batch, out uint fetched) == VSConstants.S_OK && fetched == 1)
            {
                projects.Add(batch[0]);
            }
            return projects;
        }
    }
}
