#include "emit.h"
#include <algorithm>
#include <cstddef>
#include <string_view>

namespace reflgen::generator
{
namespace
{
// 생성 파일은 ASCII 배너로 시작하고 BOM 을 단다(write 쪽). 경로에 한글 폴더명이 섞여도
// /utf-8 없이 컴파일하는 소비자가 원본을 잘못 읽지 않게 하려는 것이다.
constexpr std::string_view banner =
    "// <auto-generated/> Generated by reflgen. Do not edit; edit the source header instead.";

// 줄 수를 세며 쌓는다 — #line 으로 원본 위치를 가리켰다가 생성 파일 위치로 되돌리려면
// 지금 몇 번째 줄인지 알아야 한다.
class text_builder
{
  public:
    // 식이 여러 줄일 수 있다(줄바꿈을 품은 raw 문자열 리터럴) — 줄 수는 실제 개행으로 센다.
    void line(std::string_view text = {})
    {
        text_ += text;
        text_ += '\n';
        lines_ += static_cast<std::size_t>(std::count(text.begin(), text.end(), '\n')) + 1;
    }

    // 다음 줄이 원본의 이 위치로 보고되게 한다.
    void point_to(const source_position& position)
    {
        line("#line " + std::to_string(position.line) + " \"" + position.file + "\"");
    }

    // 다음 줄부터 다시 생성 파일 자신의 줄 번호로 보고되게 한다.
    void point_back(const std::string& generated_path)
    {
        // 이 지시문이 lines_ + 1 번째 줄이 되므로 그다음 줄은 lines_ + 2 번째다.
        line("#line " + std::to_string(lines_ + 2) + " \"" + generated_path + "\"");
    }

    std::string take() { return std::move(text_); }

  private:
    std::string text_;
    std::size_t lines_ = 0;
};

std::string joined(const std::vector<attribute_use>& uses)
{
    std::string result;
    for (const attribute_use& use : uses)
    {
        if (!result.empty())
        {
            result += ", ";
        }
        result += use.expression;
    }
    return result;
}

struct schema_entry
{
    std::string text;
    const source_position* position = nullptr; // 있으면 이 항목의 오류가 원본을 가리킨다
};

void emit_class(text_builder& out, const class_model& model, const std::string& generated_path)
{
    std::vector<schema_entry> entries;
    for (const std::string& base : model.bases)
    {
        entries.push_back({"::reflgen::base<" + base + ">", nullptr});
    }
    for (const field_model& field : model.fields)
    {
        std::string text = "::reflgen::field<&T::" + field.name + ">.named(\"" + field.name + "\")";
        if (!field.attributes.empty())
        {
            text += ".with(" + joined(field.attributes) + ")";
        }
        entries.push_back({std::move(text), &field.position});
    }
    for (const method_model& method : model.methods)
    {
        std::string text = "::reflgen::method<&T::" + method.name + ">.named(\"" + method.name + "\")";
        if (!method.parameters.empty())
        {
            text += ".parameters(";
            for (std::size_t i = 0; i < method.parameters.size(); ++i)
            {
                text += (i == 0 ? "\"" : ", \"") + method.parameters[i] + "\"";
            }
            text += ")";
        }
        if (!method.attributes.empty())
        {
            text += ".with(" + joined(method.attributes) + ")";
        }
        entries.push_back({std::move(text), &method.position});
    }

    out.line("// " + model.qualified_name + " - " + model.position.file + "(" + std::to_string(model.position.line) +
             ")");
    out.line("template<>");
    out.line("consteval auto reflgen::access::describe<" + model.qualified_name + ">()");
    out.line("{");
    // attribute 인자는 클래스가 선언된 이름공간에서 쓴 것이다 — 그 이름들이 보이게 한다.
    for (const std::string& name : model.namespaces)
    {
        out.line("    using namespace " + name + ";");
    }
    out.line("    using T = " + model.qualified_name + ";");
    // clang-format off 는 생성 파일이 포매터에 걸려도 한 줄 한 항목을 유지하게 한다.
    out.line("    // clang-format off");
    if (entries.empty())
    {
        out.line("    return ::reflgen::schema<T>()");
    }
    else
    {
        out.line("    return ::reflgen::schema<T>(");
        bool pointed = false;
        for (std::size_t i = 0; i < entries.size(); ++i)
        {
            if (entries[i].position != nullptr)
            {
                out.point_to(*entries[i].position);
                pointed = true;
            }
            out.line("        " + entries[i].text + (i + 1 < entries.size() ? "," : ""));
        }
        if (pointed)
        {
            out.point_back(generated_path);
        }
        out.line("    )");
    }
    std::string tail = "        .named(" + model.schema_name + ")";
    if (!model.attributes.empty())
    {
        out.line(tail);
        out.point_to(model.attributes.front().position);
        out.line("        .with(" + joined(model.attributes) + ");");
        out.point_back(generated_path);
    }
    else
    {
        out.line(tail + ";");
    }
    out.line("    // clang-format on");
    out.line("}");
    out.line();
    out.line("template<>");
    out.line("struct reflgen::reflection<" + model.qualified_name + ">");
    out.line("{");
    out.line("    static constexpr auto value = ::reflgen::access::describe<" + model.qualified_name + ">();");
    out.line("};");
    out.line();
}

void emit_enum(text_builder& out, const enum_model& model)
{
    out.line("// " + model.qualified_name + " - " + model.position.file + "(" + std::to_string(model.position.line) +
             ")");
    out.line("template<>");
    out.line("struct reflgen::reflection<" + model.qualified_name + ">");
    out.line("{");
    if (model.enumerators.empty())
    {
        out.line("    static constexpr std::array<::reflgen::enum_entry<" + model.qualified_name + ">, 0> value{};");
    }
    else
    {
        out.line("    static constexpr std::array value = {");
        for (std::size_t i = 0; i < model.enumerators.size(); ++i)
        {
            const std::string& name = model.enumerators[i];
            out.line("        ::reflgen::enum_entry<" + model.qualified_name + ">{\"" + name + "\", " +
                     model.qualified_name + "::" + name + "}" + (i + 1 < model.enumerators.size() ? "," : ""));
        }
        out.line("    };");
    }
    out.line("};");
    out.line();
}
} // namespace

std::string emit_header(const header_model& header, const std::string& generated_path)
{
    text_builder out;
    out.line(banner);
    out.line("// source: " + header.path);
    out.line("#pragma once");
    out.line("#include \"reflgen/reflgen.h\"");
    out.line("#include <array>");
    out.line("#include \"" + header.path + "\"");
    out.line();
    for (const enum_model& model : header.enums)
    {
        emit_enum(out, model);
    }
    for (const class_model& model : header.classes)
    {
        emit_class(out, model, generated_path);
    }
    return out.take();
}

std::string emit_module_header(const std::string& module_name)
{
    text_builder out;
    out.line(banner);
    out.line("#pragma once");
    out.line("#include \"reflgen/runtime/registry.h\"");
    out.line();
    out.line("namespace reflgen::generated");
    out.line("{");
    out.line("// Registers every [[reflgen::reflect]] class of module '" + module_name + "' in target.");
    out.line("// Call it once at startup before reading polymorphic pointers.");
    out.line("void register_" + module_name + "(::reflgen::registry& target = ::reflgen::default_registry());");
    out.line("} // namespace reflgen::generated");
    return out.take();
}

std::string emit_module_source(const std::string& module_name, const std::vector<header_model>& headers,
                               const std::vector<std::string>& generated_names)
{
    text_builder out;
    out.line(banner);
    out.line("#include \"reflgen_" + module_name + ".h\"");
    for (const std::string& name : generated_names)
    {
        out.line("#include \"" + name + "\"");
    }
    out.line();
    out.line("namespace reflgen::generated");
    out.line("{");
    out.line("void register_" + module_name + "(::reflgen::registry& target)");
    out.line("{");
    std::size_t count = 0;
    for (const header_model& header : headers)
    {
        for (const class_model& model : header.classes)
        {
            out.line("    target.add<" + model.qualified_name + ">();");
            ++count;
        }
    }
    if (count == 0)
    {
        out.line("    static_cast<void>(target);");
    }
    out.line("}");
    out.line("} // namespace reflgen::generated");
    return out.take();
}
} // namespace reflgen::generator
