#include "interop.h"
#include <algorithm>
#include <cstdint>
#include <map>
#include <set>
#include <string_view>
#include <utility>

namespace reflgen::generator
{
    namespace
    {
        constexpr std::string_view banner =
            "// <auto-generated/> Generated by reflgen. Do not edit; edit the source header instead.";

        enum class interop_target
        {
            none,
            c,
            csharp,
        };

        struct annotation_policy
        {
            interop_target target = interop_target::none;
            bool has_interop = false;
            bool has_lifetime = false;
            bool borrowed = false;
        };

        struct lowered_type
        {
            std::string native;
            std::string c;
            std::string csharp;
            long long native_size = -1;
            bool is_bool = false;
            bool is_signed = false;
            bool is_floating = false;
        };

        struct lowered_method
        {
            const method_model* model = nullptr;
            std::string symbol;
            interop_target target = interop_target::none;
            lowered_type result;
            std::vector<lowered_type> parameters;
        };

        struct lowered_class
        {
            const class_model* model = nullptr;
            std::string handle;
            std::vector<lowered_method> methods;
        };

        bool is_identifier(std::string_view value)
        {
            const auto is_letter = [](char c)
            {
                return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_';
            };
            if (value.empty() || !is_letter(value.front()))
            {
                return false;
            }
            return std::all_of(value.begin(), value.end(), [&](char c)
                               { return is_letter(c) || (c >= '0' && c <= '9'); });
        }

        bool is_qualified_name(std::string_view value, std::string_view separator)
        {
            while (true)
            {
                const std::size_t end = value.find(separator);
                if (!is_identifier(value.substr(0, end)))
                {
                    return false;
                }
                if (end == std::string_view::npos)
                {
                    return true;
                }
                value.remove_prefix(end + separator.size());
            }
        }

        bool has_control_character(std::string_view value)
        {
            return std::any_of(value.begin(), value.end(), [](unsigned char c) { return c < 32 || c == 127; }) ||
                   value.find("\xc2\x85") != std::string_view::npos ||
                   value.find("\xe2\x80\xa8") != std::string_view::npos ||
                   value.find("\xe2\x80\xa9") != std::string_view::npos;
        }

        std::string string_literal(std::string_view value)
        {
            std::string result = "\"";
            for (const char c : value)
            {
                if (c == '\\' || c == '"')
                {
                    result += '\\';
                }
                result += c;
            }
            return result + "\"";
        }

        std::string symbol_component(std::string_view value)
        {
            std::string result;
            for (std::size_t i = 0; i < value.size(); ++i)
            {
                if (value[i] == ':' && i + 1 < value.size() && value[i + 1] == ':')
                {
                    result += '_';
                    ++i;
                }
                else
                {
                    result += value[i];
                }
            }
            return result;
        }

        std::string uppercase(std::string value)
        {
            for (char& c : value)
            {
                if (c >= 'a' && c <= 'z')
                {
                    c = static_cast<char>(c - 'a' + 'A');
                }
            }
            return value;
        }

        std::string escaped_namespace(std::string_view value)
        {
            std::string result = "@";
            for (const char c : value)
            {
                result += c;
                if (c == '.')
                {
                    result += '@';
                }
            }
            return result;
        }

        // 인자를 평가하지 않는다. 정확히 한 개의 일반 문자열 token 만 허용한다.
        std::string annotation_argument(const attribute_use& attribute, diagnostics& report)
        {
            if (!attribute.has_arguments || attribute.argument_tokens.size() != 1)
            {
                report.error("RG0200", attribute.position,
                             "reflgen::" + attribute.name + " requires one ordinary string literal argument");
                return {};
            }
            const std::string& token = attribute.argument_tokens.front();
            if (token.size() < 2 || token.front() != '"' || token.back() != '"' ||
                token.find('\\') != std::string::npos || has_control_character(token))
            {
                report.error("RG0200", attribute.position,
                             "reflgen::" + attribute.name + " requires an unescaped ordinary string literal");
                return {};
            }
            return token.substr(1, token.size() - 2);
        }

        annotation_policy read_policy(const std::vector<attribute_use>& attributes, bool is_class,
                                      diagnostics& report)
        {
            annotation_policy result;
            for (const attribute_use& attribute : attributes)
            {
                if (attribute.scope != "reflgen" ||
                    (attribute.name != "interop" && attribute.name != "lifetime"))
                {
                    continue;
                }
                const bool is_interop = attribute.name == "interop";
                bool& seen = is_interop ? result.has_interop : result.has_lifetime;
                if (seen)
                {
                    report.error("RG0200", attribute.position,
                                 "duplicate or conflicting reflgen::" + attribute.name + " annotation");
                }
                seen = true;
                const std::string argument = annotation_argument(attribute, report);
                if (is_interop)
                {
                    if (argument == "c" || argument == "csharp")
                    {
                        result.target = argument == "c" ? interop_target::c : interop_target::csharp;
                    }
                    else
                    {
                        report.error("RG0200", attribute.position,
                                     "reflgen::interop supports only \"c\" or \"csharp\"");
                    }
                }
                else
                {
                    result.borrowed = argument == "borrowed";
                    if (!is_class)
                    {
                        report.error("RG0200", attribute.position,
                                     "reflgen::lifetime is supported only on an interop class");
                    }
                    if (!result.borrowed)
                    {
                        report.error("RG0200", attribute.position,
                                     "reflgen::lifetime supports only \"borrowed\"; ownership is not inferred");
                    }
                }
            }
            return result;
        }

        std::string unqualified_primitive(std::string value)
        {
            if (value.starts_with("const "))
            {
                value.erase(0, 6);
            }
            if (value.ends_with(" const"))
            {
                value.erase(value.size() - 6);
            }
            return value;
        }

        bool lower_type(const declaration_type& type, bool allow_void, const source_position& position,
                        lowered_type& result, diagnostics& report)
        {
            result.native = unqualified_primitive(type.canonical_spelling);
            result.native_size = type.size_bytes;
            if (!type.is_volatile && type.kind == "void" && allow_void && result.native == "void")
            {
                result.c = "void";
                result.csharp = "void";
                return true;
            }
            if (!type.is_volatile && type.kind == "bool" && result.native == "bool" && type.size_bytes > 0)
            {
                result.c = "uint8_t";
                result.csharp = "byte";
                result.is_bool = true;
                return true;
            }
            const bool signed_integer = type.kind == "signed_integer";
            const bool unsigned_integer = type.kind == "unsigned_integer";
            const std::set<std::string> signed_types = {"char", "signed char", "short", "int", "long", "long long"};
            const std::set<std::string> unsigned_types = {"char", "unsigned char", "unsigned short", "unsigned int",
                                                          "unsigned long", "unsigned long long"};
            if (!type.is_volatile &&
                ((signed_integer && signed_types.contains(result.native)) ||
                 (unsigned_integer && unsigned_types.contains(result.native))))
            {
                const std::map<long long, std::pair<std::string, std::string>> widths = {
                    {1, {"8", signed_integer ? "sbyte" : "byte"}},
                    {2, {"16", signed_integer ? "short" : "ushort"}},
                    {4, {"32", signed_integer ? "int" : "uint"}},
                    {8, {"64", signed_integer ? "long" : "ulong"}}};
                const auto width = widths.find(type.size_bytes);
                if (width != widths.end())
                {
                    result.c = (signed_integer ? "int" : "uint") + width->second.first + "_t";
                    result.csharp = width->second.second;
                    result.is_signed = signed_integer;
                    return true;
                }
            }
            if (!type.is_volatile && type.kind == "floating_point" &&
                ((result.native == "float" && type.size_bytes == 4) ||
                 (result.native == "double" && type.size_bytes == 8)))
            {
                result.c = result.native;
                result.csharp = result.native;
                result.is_floating = true;
                return true;
            }
            report.error("RG0202", position,
                         "unsupported interop type '" + type.spelling + "' (canonical '" + type.canonical_spelling +
                             "'); only bool, 8/16/32/64-bit integers, float and double by value are supported" +
                             (allow_void ? ", or void as a return type" : ""));
            return false;
        }

        void append_contract(std::string& contract, std::string_view value)
        {
            contract += std::to_string(value.size()) + ":";
            contract += value;
            contract += ';';
        }

        void append_type_contract(std::string& contract, const lowered_type& type)
        {
            append_contract(contract, type.native);
            append_contract(contract, std::to_string(type.native_size));
            append_contract(contract, type.c);
            append_contract(contract, type.csharp);
            append_contract(contract, type.is_bool ? "bool:nonzero-input:zero-or-one-output" : "numeric-value");
        }

        std::string fingerprint_of(std::string_view contract)
        {
            std::uint64_t hash = 14695981039346656037ULL;
            for (const unsigned char c : contract)
            {
                hash ^= c;
                hash *= 1099511628211ULL;
            }
            constexpr char digits[] = "0123456789abcdef";
            std::string result(16, '0');
            for (std::size_t i = result.size(); i > 0; --i)
            {
                result[i - 1] = digits[hash & 15U];
                hash >>= 4U;
            }
            return result;
        }

        std::string calling_convention_macro(const std::string& macro)
        {
            return "#if defined(_MSC_VER)\n#define " + macro + " __cdecl\n" +
                   "#elif defined(__i386__)\n#define " + macro + " __attribute__((cdecl))\n" +
                   "#else\n#define " + macro + "\n#endif\n";
        }

        std::string c_parameters(const lowered_class& owner, const lowered_method& method)
        {
            std::string result = owner.handle + "* receiver";
            for (std::size_t i = 0; i < method.parameters.size(); ++i)
            {
                result += ", " + method.parameters[i].c + " argument_" + std::to_string(i);
            }
            if (method.result.c != "void")
            {
                result += ", " + method.result.c + "* result";
            }
            return result;
        }

        void append_static_asserts(std::string& output, const lowered_type& type, std::set<std::string>& seen)
        {
            if (type.c == "void" || !seen.insert(type.native).second)
            {
                return;
            }
            output += "static_assert(sizeof(" + type.native + ") == " + std::to_string(type.native_size) +
                      ", \"reflgen interop: regenerate bindings for this target\");\n";
            if (type.is_floating)
            {
                output += "static_assert(::std::numeric_limits<" + type.native +
                          ">::is_iec559 && ::std::numeric_limits<" + type.native +
                          ">::radix == 2 && ::std::numeric_limits<" + type.native + ">::digits == " +
                          (type.native == "float" ? "24" : "53") +
                          ", \"reflgen interop requires IEEE 754 binary32/binary64\");\n";
            }
            else if (!type.is_bool)
            {
                output += "static_assert(::std::numeric_limits<" + type.native + ">::is_signed == " +
                          (type.is_signed ? "true" : "false") +
                          ", \"reflgen interop: native integer signedness changed\");\n";
                output += "static_assert(::std::numeric_limits<" + type.native + ">::digits == " +
                          std::to_string(type.native_size * 8 - (type.is_signed ? 1 : 0)) +
                          ", \"reflgen interop requires integers without padding bits\");\n";
            }
        }

        void append_thunk(std::string& output, const lowered_class& owner, const lowered_method& method,
                          const std::string& prefix, const std::string& macro)
        {
            output += "extern \"C\" " + macro + "_EXPORT int32_t " + macro + "_CDECL " + method.symbol + "(" +
                      c_parameters(owner, method) + ")\n{\n";
            output += "    if (receiver == nullptr";
            if (method.result.c != "void")
            {
                output += " || result == nullptr";
            }
            output += ")\n    {\n        return " + prefix + "_status_invalid_argument;\n    }\n";
            output += "    try\n    {\n        ";
            if (method.result.c != "void")
            {
                output += "const auto value = ";
            }
            output += "(reinterpret_cast<::" + owner.model->qualified_name + "*>(receiver)->" + method.model->name +
                      ")(";
            for (std::size_t i = 0; i < method.parameters.size(); ++i)
            {
                if (i != 0)
                {
                    output += ", ";
                }
                const lowered_type& parameter = method.parameters[i];
                const std::string argument = "argument_" + std::to_string(i);
                output += parameter.is_bool ? "(" + argument + " != 0)"
                                            : "static_cast<" + parameter.native + ">(" + argument + ")";
            }
            output += ");\n";
            if (method.result.c != "void")
            {
                output += "        *result = static_cast<" + method.result.c + ">(" +
                          (method.result.is_bool ? "value ? 1 : 0" : "value") + ");\n";
            }
            output += "        return " + prefix + "_status_ok;\n    }\n    catch (...)\n    {\n        return " +
                      prefix + "_status_exception;\n    }\n}\n\n";
        }
    } // namespace

    interop_output emit_interop(const std::vector<class_model>& exports, const target_model& target,
                                const interop_options& options, diagnostics& report)
    {
        const source_position option_position;
        if (!is_identifier(options.module_name))
        {
            report.error("RG0200", option_position, "interop module name must be an ASCII identifier");
        }
        const std::string library = options.library_name.empty() ? options.module_name : options.library_name;
        if (has_control_character(library))
        {
            report.error("RG0200", option_position, "interop library name must not contain control characters");
        }
        if (!exports.empty() && (target.triple.empty() || (target.pointer_width != 32 && target.pointer_width != 64)))
        {
            report.error("RG0202", exports.front().position,
                         "interop requires a known target triple with 32-bit or 64-bit pointers");
        }
        const bool windows_target = target.triple.find("windows") != std::string::npos ||
                                    target.triple.find("mingw") != std::string::npos ||
                                    target.triple.find("win32") != std::string::npos;
        const bool linux_target = target.triple.find("-linux") != std::string::npos;
        const bool macos_target = target.triple.find("-apple-") != std::string::npos &&
                                  (target.triple.find("darwin") != std::string::npos ||
                                   target.triple.find("macos") != std::string::npos);
        const std::string architecture = target.triple.substr(0, target.triple.find('-'));
        const bool x86 = architecture == "i386" || architecture == "i486" || architecture == "i586" ||
                         architecture == "i686";
        const bool x64 = architecture == "x86_64" || architecture == "amd64";
        const bool arm64 = architecture == "aarch64" || architecture == "arm64";
        const bool supported_target = (linux_target && (x86 || x64 || arm64)) ||
                                      ((windows_target || macos_target) && (x64 || arm64));
        if (!exports.empty() && windows_target && target.pointer_width == 32)
        {
            report.error("RG0202", exports.front().position,
                         "32-bit Windows interop is not supported yet because exported symbol decoration varies");
        }
        else if (!exports.empty() &&
                 (!supported_target || (x86 && target.pointer_width != 32) ||
                  ((x64 || arm64) && target.pointer_width != 64)))
        {
            report.error("RG0202", exports.front().position,
                         "interop supports only x86/x64/arm64 Linux and x64/arm64 Windows or macOS targets");
        }

        const std::string prefix = "reflgen_" + options.module_name;
        const std::string macro = uppercase(prefix) + "_INTEROP";
        std::map<std::string, source_position> symbols;
        const auto reserve_symbol = [&](const std::string& symbol, const source_position& position)
        {
            if (!symbols.emplace(symbol, position).second)
            {
                report.error("RG0203", position, "generated interop symbol collision: '" + symbol + "'");
            }
        };
        reserve_symbol(prefix + "_abi_fingerprint", option_position);
        reserve_symbol(prefix + "_status_ok", option_position);
        reserve_symbol(prefix + "_status_invalid_argument", option_position);
        reserve_symbol(prefix + "_status_exception", option_position);

        std::vector<lowered_class> classes;
        bool has_csharp = false;
        std::string contract;
        for (const std::string& part :
             std::vector<std::string>{"reflgen-primitive-interop-v1", options.module_name, library,
                                      options.csharp_namespace, target.triple, std::to_string(target.pointer_width),
                                      "cdecl", "borrowed-exact-live-object-address-no-destruction",
                                      "status-int32:ok=0:null=1:exception=2:wrapper-writes-output-only-on-success"})
        {
            append_contract(contract, part);
        }
        std::vector<const class_model*> ordered_classes;
        for (const class_model& model : exports)
        {
            ordered_classes.push_back(&model);
        }
        std::sort(ordered_classes.begin(), ordered_classes.end(), [](const class_model* left, const class_model* right)
                  { return left->qualified_name < right->qualified_name; });
        for (const class_model* model_pointer : ordered_classes)
        {
            const class_model& model = *model_pointer;
            const annotation_policy policy = read_policy(model.attributes, true, report);
            if (policy.has_lifetime && !policy.has_interop)
            {
                report.error("RG0200", model.position, "reflgen::lifetime requires reflgen::interop on the class");
            }
            if (policy.has_interop && (!policy.has_lifetime || !policy.borrowed))
            {
                report.error("RG0200", model.position,
                             "interop classes require explicit [[reflgen::lifetime(\"borrowed\")]]");
            }
            if (policy.has_interop && (model.nested || !is_qualified_name(model.qualified_name, "::")))
            {
                report.error("RG0201", model.position,
                             "interop requires a non-nested, non-template class with an ASCII qualified name");
            }
            if (policy.has_interop &&
                (model.position.file.empty() || has_control_character(model.position.file) ||
                 model.position.file.find('"') != std::string::npos ||
                 model.position.file.find('\\') != std::string::npos))
            {
                report.error("RG0201", model.position, "interop requires a normalized, includable source header path");
            }
            has_csharp = has_csharp || policy.target == interop_target::csharp;
            lowered_class owner;
            owner.model = &model;
            owner.handle = prefix + "_" + symbol_component(model.qualified_name) + "_handle";
            if (policy.has_interop)
            {
                reserve_symbol(owner.handle, model.position);
                append_contract(contract, "class");
                append_contract(contract, model.qualified_name);
                append_contract(contract, policy.target == interop_target::csharp ? "csharp" : "c");
                append_contract(contract, "borrowed");
            }
            for (const field_model& field : model.fields)
            {
                const annotation_policy field_policy = read_policy(field.attributes, false, report);
                if (field_policy.has_interop)
                {
                    report.error("RG0201", field.position, "interop field exports are not supported; select a method");
                }
            }
            std::map<std::string, std::size_t> method_counts;
            std::vector<const method_model*> ordered_methods;
            for (const method_model& method : model.methods)
            {
                ++method_counts[method.name];
                ordered_methods.push_back(&method);
            }
            std::sort(ordered_methods.begin(), ordered_methods.end(),
                      [](const method_model* left, const method_model* right) { return left->name < right->name; });
            for (const method_model* method_pointer : ordered_methods)
            {
                const method_model& method = *method_pointer;
                const annotation_policy method_policy = read_policy(method.attributes, false, report);
                if (!method_policy.has_interop)
                {
                    continue;
                }
                if (!policy.has_interop)
                {
                    report.error("RG0200", method.position, "selected interop method requires reflgen::interop on its class");
                }
                if (method_policy.target == interop_target::csharp && policy.target != interop_target::csharp)
                {
                    report.error("RG0200", method.position, "a C# method requires a C# interop class target");
                }
                if (method.access != "public" || method.is_static || method.is_deleted || method.is_consteval ||
                    !method.declaration_specifiers_known || !method.qualifiers_known || method.is_volatile ||
                    method.is_variadic ||
                    method.ref_qualifier != "none" || method.is_overloaded || method_counts[method.name] > 1 ||
                    !is_identifier(method.name))
                {
                    report.error("RG0201", method.position,
                                 "interop supports only public, nonstatic, non-deleted, non-consteval, non-overloaded "
                                 "ordinary methods with known declaration specifiers and qualifiers and without "
                                 "volatile/ref qualifiers or variadic parameters "
                                 "(const methods are supported)");
                }
                lowered_method lowered;
                lowered.model = &method;
                lowered.target = method_policy.target;
                lowered.symbol = prefix + "_" + symbol_component(model.qualified_name) + "_" + method.name;
                reserve_symbol(lowered.symbol, method.position);
                lower_type(method.return_type, true, method.position, lowered.result, report);
                for (const parameter_model& parameter : method.parameter_declarations)
                {
                    lowered_type type;
                    lower_type(parameter.type, false, parameter.position, type, report);
                    lowered.parameters.push_back(std::move(type));
                }
                append_contract(contract, "method");
                append_contract(contract, lowered.symbol);
                append_contract(contract, method_policy.target == interop_target::csharp ? "csharp" : "c");
                append_contract(contract, method.signature);
                append_contract(contract, method.is_const ? "const" : "mutable");
                append_contract(contract, method.calling_convention);
                append_contract(contract, method.exception_specification);
                append_type_contract(contract, lowered.result);
                append_contract(contract, std::to_string(lowered.parameters.size()));
                for (const lowered_type& parameter : lowered.parameters)
                {
                    append_type_contract(contract, parameter);
                }
                owner.methods.push_back(std::move(lowered));
            }
            if (policy.has_interop)
            {
                classes.push_back(std::move(owner));
            }
        }
        if (has_csharp && !is_qualified_name(options.csharp_namespace, "."))
        {
            report.error("RG0200", option_position, "C# namespace must contain dot-separated ASCII identifiers");
        }
        if (report.has_errors())
        {
            return {};
        }

        interop_output output;
        output.fingerprint = fingerprint_of(contract);
        std::string& header = output.c_header;
        header = std::string(banner) + "\n#pragma once\n#include <stdint.h>\n\n";
        header += "// Target: " + target.triple + "; regenerate for another target.\n";
        header += "// Handles borrow the exact address of a live object of the stated C++ type.\n";
        header += "// The caller owns its lifetime, alignment, thread safety and correct type.\n";
        header += "// Null is checked; dangling, wrong-type and arbitrary nonnull pointers are undefined behavior.\n";
        header += "// No constructor, destruction, ownership transfer, RTTI lookup or stale-handle registry is provided.\n";
        header += "// bool uses uint8_t: any nonzero input is true; output is 0 or 1.\n";
        header += "// Wrappers write results only after successful invocation. Exceptions become status_exception.\n";
        header += "// The fingerprint detects contract changes, not malicious code or invalid handles.\n\n";
        header += calling_convention_macro(macro + "_CDECL");
        header += "\n#ifdef __cplusplus\nextern \"C\"\n{\n#endif\n\n";
        header += "enum\n{\n    " + prefix + "_status_ok = 0,\n    " + prefix +
                  "_status_invalid_argument = 1,\n    " + prefix + "_status_exception = 2\n};\n\n";
        header += "uint64_t " + macro + "_CDECL " + prefix + "_abi_fingerprint(void);\n\n";
        for (const lowered_class& owner : classes)
        {
            header += "// Borrowed " + owner.model->qualified_name + "\n";
            header += "typedef struct " + owner.handle + " " + owner.handle + ";\n";
            for (const lowered_method& method : owner.methods)
            {
                header += "int32_t " + macro + "_CDECL " + method.symbol + "(" + c_parameters(owner, method) + ");\n";
            }
            header += '\n';
        }
        header += "#ifdef __cplusplus\n}\n#endif\n\n#undef " + macro + "_CDECL\n";

        std::string& source = output.cpp_source;
        source = std::string(banner) + "\n#include " + string_literal(prefix + ".h") + "\n#include " +
                 string_literal(prefix + "_interop.h") + "\n";
        std::set<std::string> headers;
        for (const lowered_class& owner : classes)
        {
            if (headers.insert(owner.model->position.file).second)
            {
                source += "#include " + string_literal(owner.model->position.file) + "\n";
            }
        }
        source += "#include <climits>\n#include <limits>\n\n";
        if (supported_target && target.pointer_width != 0)
        {
            const std::string architecture_test = x86 ? "defined(__i386__) || defined(_M_IX86)"
                                                  : x64 ? "defined(__x86_64__) || defined(_M_X64)"
                                                        : "defined(__aarch64__) || defined(__arm64__) || defined(_M_ARM64)";
            const std::string os_test = windows_target ? "defined(_WIN32)"
                                       : linux_target ? "defined(__linux__)"
                                                      : "defined(__APPLE__) && defined(__MACH__)";
            source += "#if !(" + os_test + ") || !(" + architecture_test +
                      ") || defined(_M_ARM64EC) || defined(__arm64ec__)\n";
            source += "#error reflgen interop: regenerate with the matching compiler --target\n#endif\n\n";
            if (macos_target)
            {
                source += "#if defined(__APPLE__) && defined(__MACH__)\n#include <TargetConditionals.h>\n";
                source += "#if !TARGET_OS_OSX\n#error reflgen interop: macOS bindings cannot target another Apple OS\n";
                source += "#endif\n#endif\n\n";
            }
        }
        source += calling_convention_macro(macro + "_CDECL");
        source += "#if defined(_WIN32)\n#define " + macro + "_EXPORT __declspec(dllexport)\n#else\n#define " + macro +
                  "_EXPORT __attribute__((visibility(\"default\")))\n#endif\n\n";
        source += "static_assert(CHAR_BIT == 8, \"reflgen interop requires 8-bit bytes\");\n";
        if (target.pointer_width != 0)
        {
            source += "static_assert(sizeof(void*) * CHAR_BIT == " + std::to_string(target.pointer_width) +
                      ", \"reflgen interop: regenerate bindings for this target\");\n";
        }
        std::set<std::string> checked_types;
        for (const lowered_class& owner : classes)
        {
            for (const lowered_method& method : owner.methods)
            {
                append_static_asserts(source, method.result, checked_types);
                for (const lowered_type& parameter : method.parameters)
                {
                    append_static_asserts(source, parameter, checked_types);
                }
            }
        }
        source += "\n// ABI contract fingerprint (FNV-1a 64-bit); this is not a cryptographic signature.\n";
        source += "extern \"C\" " + macro + "_EXPORT uint64_t " + macro + "_CDECL " + prefix +
                  "_abi_fingerprint(void)\n{\n    return 0x" + output.fingerprint + "ULL;\n}\n\n";
        for (const lowered_class& owner : classes)
        {
            for (const lowered_method& method : owner.methods)
            {
                append_thunk(source, owner, method, prefix, macro);
            }
        }
        source += "#undef " + macro + "_EXPORT\n#undef " + macro + "_CDECL\n";

        output.csharp_source = std::string(banner) + "\n// No C# types were selected for this module.\n";
        if (has_csharp)
        {
            std::string& managed = output.csharp_source;
            managed = std::string(banner) + "\n\n";
            managed += "namespace " + escaped_namespace(options.csharp_namespace) + "\n{\n";
            managed += "    // Raw C ABI declarations; receiver is a borrowed native address, never a managed object.\n";
            managed += "    // The caller must keep the exact native object alive and coordinate concurrent access.\n";
            managed += "    // There is no ownership, Dispose, stale-handle validation or automatic error translation.\n";
            managed += "    // Compare the native fingerprint with AbiFingerprint before exchanging handles.\n";
            managed += "    // bool parameters/results are bytes: nonzero input is true; output is 0 or 1.\n";
            managed += "    // Output values are valid only on StatusOk. DllImport does not promise NativeAOT support.\n";
            managed += "    public static class " + prefix + "_interop\n    {\n";
            managed += "        public const string LibraryName = " + string_literal(library) + ";\n";
            managed += "        public const ulong AbiFingerprint = 0x" + output.fingerprint + "UL;\n";
            managed += "        public const int StatusOk = 0;\n        public const int StatusInvalidArgument = 1;\n";
            managed += "        public const int StatusException = 2;\n\n";
            const auto append_import = [&](const std::string& symbol)
            {
                managed += "        [global::System.Runtime.InteropServices.DllImport(LibraryName, EntryPoint = " +
                           string_literal(symbol) + ", ExactSpelling = true, CallingConvention = " +
                           "global::System.Runtime.InteropServices.CallingConvention.Cdecl)]\n";
            };
            append_import(prefix + "_abi_fingerprint");
            managed += "        public static extern ulong " + prefix + "_abi_fingerprint();\n";
            for (const lowered_class& owner : classes)
            {
                for (const lowered_method& method : owner.methods)
                {
                    if (method.target != interop_target::csharp)
                    {
                        continue;
                    }
                    managed += '\n';
                    append_import(method.symbol);
                    managed += "        public static extern int " + method.symbol + "(nint receiver";
                    for (std::size_t i = 0; i < method.parameters.size(); ++i)
                    {
                        managed += ", " + method.parameters[i].csharp + " argument_" + std::to_string(i);
                    }
                    if (method.result.c != "void")
                    {
                        managed += ", out " + method.result.csharp + " result";
                    }
                    managed += ");\n";
                }
            }
            managed += "    }\n}\n";
        }
        return output;
    }
} // namespace reflgen::generator
